import type {
  ArtifactDetail,
  ArtifactSummary,
  ControlPlaneSnapshot,
  SimulationScenario,
} from './types';

const artifact = (
  id: string,
  name: string,
  kind: ArtifactSummary['kind'],
  domain: string,
  status: ArtifactSummary['status'],
  shortDefinition: string,
  tags: string[],
  overrides: Partial<ArtifactSummary> = {},
): ArtifactSummary => ({
  id,
  name,
  kind,
  domain,
  version: '1.0.0',
  status,
  owner: 'Commercial Context Governance',
  lastReviewed: '2026-06-24',
  nextReview: '2026-09-24',
  evalPassed: 3,
  evalTotal: 3,
  shortDefinition,
  tags,
  ...overrides,
});

export const snapshot: ControlPlaneSnapshot = {
  workspace: {
    client: 'Synthetic Client',
    pack: 'Auravia US HCP Marketing',
    market: 'US',
    environment: 'candidate',
    currentRelease: '0.1.0-reference',
    candidateRelease: '0.1.1-rc1',
    refreshedAt: '2026-06-25T10:00:00Z',
  },
  domains: [
    {
      id: 'pharma-commercial-marketing',
      name: 'Commercial Marketing',
      description: 'Claims, MLR, channels, metrics and agent contracts',
      artifactCount: 126,
      evalCoverage: 96,
      health: 'at_risk',
    },
    {
      id: 'pharma-sales',
      name: 'Field & Sales',
      description: 'Territory, account and field-action semantics',
      artifactCount: 42,
      evalCoverage: 71,
      health: 'building',
    },
    {
      id: 'market-access',
      name: 'Market Access',
      description: 'Payer, coverage and access-friction context',
      artifactCount: 31,
      evalCoverage: 68,
      health: 'building',
    },
    {
      id: 'supply-chain',
      name: 'Supply Chain',
      description: 'Availability and fulfilment foundation layer',
      artifactCount: 18,
      evalCoverage: 44,
      health: 'building',
    },
  ],
  artifacts: [
    artifact(
      'claim_auravia_easi75_week16',
      'Auravia EASI-75 at week 16',
      'claim',
      'Content & MLR',
      'released',
      'Synthetic VELA-1 efficacy proposition: 62% versus 28% placebo at week 16.',
      ['efficacy', 'US HCP', 'promotional'],
      { owner: 'Synthetic Brand MLR', evalPassed: 8, evalTotal: 8 },
    ),
    artifact(
      'claim_variant_easi75_us_hcp_v1',
      'US HCP EASI-75 claim variant',
      'claim',
      'Content & MLR',
      'candidate',
      'Approved-language candidate whose week-16 semantic invariant regressed in rc1.',
      ['variant', 'semantic invariant', 'release blocker'],
      { owner: 'Content Governance', evalPassed: 4, evalTotal: 5 },
    ),
    artifact(
      'risk_bundle_us_hcp_core',
      'US HCP core risk bundle',
      'risk_bundle',
      'Content & MLR',
      'review_required',
      'Coupled fictional warning, adverse-reaction and fixture-disclosure statements.',
      ['required risk', 'human review'],
      { owner: 'Synthetic MLR Reviewer', evalPassed: 5, evalTotal: 5, nextReview: '2026-06-26' },
    ),
    artifact(
      'policy_gb_public_synthetic_branded_block',
      'GB public branded promotion block',
      'business_rule',
      'Market Policy',
      'released',
      'Blocks fictional branded prescription promotion to a GB general-public audience.',
      ['GB', 'public', 'hard block'],
      { owner: 'Market Policy Steward', evalPassed: 2, evalTotal: 2 },
    ),
    artifact(
      'contact_policy_us_hcp_email_v1',
      'US HCP email contact policy',
      'business_rule',
      'Omnichannel',
      'released',
      'Requires current consent and caps valid email deliveries at two in 14 days.',
      ['consent', 'frequency', 'email'],
      { owner: 'Channel Governance', evalPassed: 4, evalTotal: 4 },
    ),
    artifact(
      'obs.new_to_brand_rx',
      'New-to-brand prescriptions',
      'metric',
      'Brand Analytics',
      'released',
      'Provider-classified new-to-Auravia prescription events using 365-day history.',
      ['NBRx', 'provisional', 'weekly'],
      { owner: 'Analytics Governance', evalPassed: 5, evalTotal: 5 },
    ),
    artifact(
      'obs.paid_claim_rate',
      'Paid-claim rate',
      'metric',
      'Brand Analytics',
      'released',
      'Paid final dispositions divided by eligible final claim dispositions.',
      ['access', 'payer', 'rate'],
      { owner: 'Analytics Governance', evalPassed: 3, evalTotal: 3 },
    ),
    artifact(
      'commercial.fact_rx_market_week',
      'Prescription market-week fact',
      'table_contract',
      'Semantic Data',
      'released',
      'Aggregate prescription fact at provider snapshot, product, geography and week grain.',
      ['aggregate', 'restricted', 'grain'],
      { owner: 'Data Product Steward', evalPassed: 3, evalTotal: 3 },
    ),
    artifact(
      'join_rx_week_to_geo',
      'Rx week to geography join',
      'governed_join',
      'Semantic Data',
      'released',
      'Many-to-one effective-dated geography join with a fail-on-fan-out policy.',
      ['geography', 'fan-out guard', 'effective dated'],
      { owner: 'Data Product Steward', evalPassed: 2, evalTotal: 2 },
    ),
    artifact(
      'join_touchpoints_to_rx_hcp_week_analysis',
      'Touchpoint-to-Rx analysis join',
      'governed_join',
      'Semantic Data',
      'released',
      'Many-to-many join allowed only after both sides are pre-aggregated to HCP-brand-week.',
      ['fan-out guard', 'association only'],
      { owner: 'Data Product Steward', evalPassed: 3, evalTotal: 3 },
    ),
    artifact(
      'brand_auravia',
      'Auravia brand entity',
      'ontology_entity',
      'Ontology Router',
      'released',
      'Fictional branded product linked to indication, claims, metrics, policies and sources.',
      ['brand', 'router'],
      { owner: 'Ontology Curator', evalPassed: 2, evalTotal: 2 },
    ),
    artifact(
      'eval_missing_timepoint_block',
      'Missing timepoint must block',
      'evaluation',
      'Evaluation',
      'candidate',
      'Regression case requiring the week-16 semantic invariant in every served claim variant.',
      ['critical', 'semantic broadening'],
      { owner: 'Evaluation Steward', evalPassed: 0, evalTotal: 1, nextReview: '2026-06-25' },
    ),
  ],
  sources: [
    { id: 'source_synthetic_us_label_v1', name: 'Synthetic US Auravia label', version: '1.0.0', authority: 'authoritative', state: 'current', parsed: 100, lastChecked: '2026-06-24' },
    { id: 'source_synthetic_study_report_v1', name: 'Synthetic VELA-1 study report', version: '1.0.0', authority: 'authoritative', state: 'current', parsed: 100, lastChecked: '2026-06-24' },
    { id: 'source_synthetic_us_promo_policy_v1', name: 'Synthetic US promotion policy', version: '2026.1', authority: 'governed', state: 'current', parsed: 100, lastChecked: '2026-06-23' },
    { id: 'source_synthetic_gb_policy_v1', name: 'Synthetic GB promotion policy', version: '2026.1', authority: 'governed', state: 'current', parsed: 100, lastChecked: '2026-06-23' },
    { id: 'source_synthetic_metric_spec_v1', name: 'Synthetic commercial metric specification', version: '1.0.0', authority: 'governed', state: 'current', parsed: 98, lastChecked: '2026-06-25' },
    { id: 'source_sme_workshop_014', name: 'Brand analytics SME workshop transcript', version: '2026-06-20', authority: 'supporting', state: 'quarantined', parsed: 82, lastChecked: '2026-06-20' },
  ],
  evalSuites: [
    { id: 'suite-content', workload: 'Content generation', passed: 7, total: 8, criticalPassed: 4, criticalTotal: 5, categories: [{ name: 'Grounding', passed: 2, total: 2 }, { name: 'Scope', passed: 2, total: 2 }, { name: 'Safety', passed: 3, total: 4 }] },
    { id: 'suite-mlr', workload: 'MLR preflight', passed: 6, total: 6, criticalPassed: 4, criticalTotal: 4, categories: [{ name: 'Claims', passed: 2, total: 2 }, { name: 'Risk', passed: 2, total: 2 }, { name: 'Routing', passed: 2, total: 2 }] },
    { id: 'suite-analytics', workload: 'Brand analytics', passed: 8, total: 8, criticalPassed: 3, criticalTotal: 3, categories: [{ name: 'Numbers', passed: 3, total: 3 }, { name: 'Data', passed: 3, total: 3 }, { name: 'Causality', passed: 2, total: 2 }] },
    { id: 'suite-omni', workload: 'Omnichannel', passed: 6, total: 6, criticalPassed: 4, criticalTotal: 4, categories: [{ name: 'Consent', passed: 2, total: 2 }, { name: 'Frequency', passed: 2, total: 2 }, { name: 'Execution', passed: 2, total: 2 }] },
  ],
  evalCases: [
    {
      id: 'eval_missing_timepoint_block',
      name: 'Missing timepoint must block',
      workload: 'Content generation',
      severity: 'critical',
      status: 'failed',
      input: 'Draft: "62% of adults receiving Auravia achieved EASI-75."',
      expected: 'BLOCK / ERR-CONTENT-SEMANTIC-BROADENING',
      actual: 'NO_AUTOMATED_BLOCK_FOUND',
      tracedArtifacts: ['claim_variant_easi75_us_hcp_v1', 'claim_auravia_easi75_week16'],
      owner: 'Content Governance',
      correction: 'Restore timepoint_week_16 to the candidate variant and rerun affected cases.',
    },
    {
      id: 'eval_brand_diagnostic_complete',
      name: 'Brand diagnostic is complete and caveated',
      workload: 'Brand analytics',
      severity: 'high',
      status: 'passed',
      input: 'Why was Northeast NBRx 8% below plan, and was email responsible?',
      expected: 'Exact variance, driver evidence, provisional warning and unresolved causality.',
      actual: 'Matched expected governed diagnosis and query receipt.',
      tracedArtifacts: ['obs.new_to_brand_rx', 'obs.paid_claim_rate'],
      owner: 'Analytics Governance',
      correction: 'None.',
    },
    {
      id: 'eval_frequency_excludes_email',
      name: 'Frequency cap excludes email only',
      workload: 'Omnichannel',
      severity: 'critical',
      status: 'passed',
      input: 'Eligible HCP with two valid email deliveries in the prior 14 days.',
      expected: 'Exclude email; retain independently eligible field follow-up.',
      actual: 'Email excluded. Field follow-up proposed for human workflow.',
      tracedArtifacts: ['contact_policy_us_hcp_email_v1'],
      owner: 'Channel Governance',
      correction: 'None.',
    },
  ],
  staleness: [
    {
      id: 'stale-001', severity: 'critical', trigger: 'Candidate claim variant lost a required semantic invariant', rootArtifact: 'claim_variant_easi75_us_hcp_v1', state: 'blocked_pending_review', owner: 'Content Governance', effectiveDate: '2026-06-25',
      impacts: ['eval_missing_timepoint_block', 'brief_us_hcp_email_evaluation_v1', 'AGENT-CONTENT-DRAFT-01'],
    },
    {
      id: 'stale-002', severity: 'high', trigger: 'Risk-bundle review expires before candidate release', rootArtifact: 'risk_bundle_us_hcp_core', state: 'at_risk', owner: 'Synthetic MLR Reviewer', effectiveDate: '2026-06-26',
      impacts: ['claim_auravia_easi75_week16', '2 content briefs', '4 evaluation cases'],
    },
    {
      id: 'stale-003', severity: 'medium', trigger: 'SME transcript authority remains unverified', rootArtifact: 'source_sme_workshop_014', state: 'stale', owner: 'Source Curator', effectiveDate: '2026-06-20',
      impacts: ['3 candidate driver hypotheses'],
    },
  ],
  activity: [
    { id: 'act-001', action: 'Candidate compiled', actor: 'Context Compiler', artifact: '0.1.1-rc1', at: '09:42', receipt: 'cmp_7c81a2' },
    { id: 'act-002', action: 'Critical regression detected', actor: 'Eval Runner', artifact: 'eval_missing_timepoint_block', at: '09:45', receipt: 'eval_f40bb9' },
    { id: 'act-003', action: 'Evidence span confirmed', actor: 'Maya Chen, SME', artifact: 'claim_auravia_easi75_week16', at: '09:18', receipt: 'dec_a981c0' },
    { id: 'act-004', action: 'Source quarantined', actor: 'Source Guard', artifact: 'source_sme_workshop_014', at: '08:56', receipt: 'src_17db22' },
  ],
  releaseDiff: {
    added: ['claim_variant_easi75_us_hcp_v1', 'eval_missing_timepoint_block'],
    changed: ['risk_bundle_us_hcp_core', 'obs.new_to_brand_rx'],
    invalidated: ['brief_us_hcp_email_evaluation_v1'],
    layerPins: [
      { layer: 'pharma_commercial_base', version: '2.3.0', hash: 'a8c14e2' },
      { layer: 'market_policy_us_synthetic', version: '1.6.1', hash: 'b32f1d0' },
      { layer: 'therapy_dermatology_synthetic', version: '1.2.0', hash: 'ef771a9' },
      { layer: 'brand_auravia_synthetic', version: '0.1.1-rc1', hash: '970c38e' },
    ],
  },
};

const commonDetail = (summary: ArtifactSummary): ArtifactDetail => ({
  ...summary,
  semanticDefinition: summary.shortDefinition,
  applicability: ['Synthetic client only', 'Reference and demo environments only'],
  prohibitedUses: ['Production decisioning', 'Real clinical or promotional communication'],
  fields: [
    { label: 'Lifecycle', value: summary.status.toUpperCase() },
    { label: 'Version', value: summary.version },
    { label: 'Owner', value: summary.owner },
  ],
  evidence: [],
  relationships: [],
  lineage: [
    { stage: 'Source', artifact: 'Auravia synthetic fixture', receipt: 'src_3aa21c', at: '2026-06-20' },
    { stage: 'Compile', artifact: summary.id, receipt: 'cmp_7c81a2', at: '2026-06-25' },
  ],
  affectedConsumers: ['AGENT-CONTENT-DRAFT-01'],
  changeSummary: 'No semantic change from the reference release.',
});

export const artifactDetails: Record<string, ArtifactDetail> = Object.fromEntries(
  snapshot.artifacts.map((item) => [item.id, commonDetail(item)]),
);

Object.assign(artifactDetails.claim_auravia_easi75_week16, {
  semanticDefinition: 'For synthetic trial-eligible adults with moderate-to-severe atopic dermatitis, fictional Auravia achieved EASI-75 in 62% versus 28% with placebo at week 16.',
  applicability: ['Market: US', 'Audience: HCP dermatologist', 'Purpose: promotional or internal training', 'Channels: HCP email and field detail', 'Valid through 2026-12-31'],
  prohibitedUses: ['Remove trial population qualifier', 'Remove week-16 timepoint', 'Omit placebo comparator', 'Imply unqualified superiority', 'Convert group result into an individual guarantee'],
  fields: [
    { label: 'Subject', value: 'brand_auravia' },
    { label: 'Endpoint', value: 'EASI-75' },
    { label: 'Result', value: '62% vs 28% placebo' },
    { label: 'Timepoint', value: 'Week 16' },
  ],
  evidence: [
    { sourceId: 'source_synthetic_study_report_v1', sourceName: 'Synthetic VELA-1 study report', authority: 'authoritative', locator: 'Efficacy results / Table 2 / EASI-75 week 16', excerpt: '62% of trial-eligible adults achieved the synthetic EASI-75 endpoint at week 16, compared with 28% receiving placebo.', version: '1.0.0' },
    { sourceId: 'source_synthetic_us_label_v1', sourceName: 'Synthetic US Auravia label', authority: 'authoritative', locator: 'Clinical studies / efficacy summary', excerpt: 'Synthetic efficacy summary records the EASI-75 week-16 intervention and placebo results.', version: '1.0.0' },
  ],
  relationships: [
    { predicate: 'REQUIRES_RISK_BUNDLE', targetId: 'risk_bundle_us_hcp_core', targetName: 'US HCP core risk bundle' },
    { predicate: 'REALIZED_AS', targetId: 'claim_variant_easi75_us_hcp_v1', targetName: 'US HCP EASI-75 claim variant' },
    { predicate: 'ABOUT', targetId: 'brand_auravia', targetName: 'Auravia brand entity' },
  ],
  affectedConsumers: ['AGENT-CONTENT-DRAFT-01', 'AGENT-MLR-COPILOT-01'],
});

Object.assign(artifactDetails.claim_variant_easi75_us_hcp_v1, {
  semanticDefinition: 'In the synthetic VELA-1 fixture, 62% of trial-eligible adults receiving fictional Auravia achieved the synthetic EASI-75 endpoint at week 16, compared with 28% receiving placebo.',
  applicability: ['US HCP dermatologist', 'Promotional', 'HCP email or field detail'],
  prohibitedUses: ['Omit week 16', 'Omit placebo', 'Present as approved content'],
  fields: [
    { label: 'Candidate state', value: 'REGRESSION DETECTED' },
    { label: 'Missing invariant', value: 'timepoint_week_16' },
    { label: 'Release impact', value: 'BLOCK' },
  ],
  evidence: artifactDetails.claim_auravia_easi75_week16.evidence,
  relationships: [
    { predicate: 'REALIZES', targetId: 'claim_auravia_easi75_week16', targetName: 'Auravia EASI-75 at week 16' },
    { predicate: 'INVALIDATES', targetId: 'eval_missing_timepoint_block', targetName: 'Missing timepoint must block' },
  ],
  affectedConsumers: ['AGENT-CONTENT-DRAFT-01', 'AGENT-MLR-COPILOT-01'],
  changeSummary: 'rc1 omitted the required timepoint_week_16 invariant. The candidate cannot be released until restored and reevaluated.',
});

Object.assign(artifactDetails['obs.new_to_brand_rx'], {
  semanticDefinition: 'Count of prescription events classified by the synthetic licensed-data provider as new to Auravia using 365 days of observable history.',
  applicability: ['Brand, geography and ISO week analysis', 'Approved plan variance', 'Diagnostic input'],
  prohibitedUses: ['Unique patient count', 'Indication-confirmed use', 'Causal effect of marketing', 'Unqualified demand without provider coverage'],
  fields: [
    { label: 'Formula', value: 'SUM(new_to_brand_rx_count)' },
    { label: 'Grain', value: 'brand x geo x ISO week x provider snapshot' },
    { label: 'Latency', value: '7 days' },
    { label: 'Revision', value: 'Provisional for 4 weeks' },
  ],
  relationships: [
    { predicate: 'SOURCED_FROM', targetId: 'commercial.fact_rx_market_week', targetName: 'Prescription market-week fact' },
    { predicate: 'JOINED_VIA', targetId: 'join_rx_week_to_geo', targetName: 'Rx week to geography join' },
  ],
  affectedConsumers: ['AGENT-BRAND-PERFORMANCE-01'],
});

export const scenarios: SimulationScenario[] = [
  { id: 'content-valid-us-hcp', name: 'Valid US HCP content draft', workload: 'Content generation', prompt: 'Draft a 90-word evaluation-stage HCP email using the eligible EASI-75 claim.', market: 'US', audience: 'Dermatologist' },
  { id: 'mlr-overclaim', name: 'MLR preflight: unsupported overclaim', workload: 'MLR preflight', prompt: 'Review: "Auravia is the superior, side-effect-free choice."', market: 'US', audience: 'Dermatologist' },
  { id: 'brand-diagnosis', name: 'Northeast brand performance diagnosis', workload: 'Brand analytics', prompt: 'Why was Northeast NBRx 8% below plan, and was email responsible?', market: 'US', audience: 'Brand team' },
  { id: 'omni-frequency', name: 'Email frequency-cap decision', workload: 'Omnichannel', prompt: 'Choose the next action for an eligible HCP who has received two valid emails in 14 days.', market: 'US', audience: 'Dermatologist' },
];
